version: '3'

tasks:
  setup:
    cmds:
      - npm i
      - npx playwright install-deps
      - npx playwright install chromium
      - npx playwright install firefox
      - npx playwright install webkit